"""单条分析与 Excel 批量分析共用的展示/导出字段。"""
from __future__ import annotations

NUMBER_HEADER = "序号"
PROJECT_HEADER = "项目名称"
PRODUCT_MODEL_HEADER = "产品型号"
LINE_HEADER = "产线"
STATION_HEADER = "工位号"
STATION_DESCRIPTION_HEADER = "工位描述"
OUTPUT_OPERATION_HEADER = "作业描述"
TRANSLATED_OPERATION_HEADER = "翻译后作业描述"

INPUT_HEADERS = (
    NUMBER_HEADER,
    PROJECT_HEADER,
    PRODUCT_MODEL_HEADER,
    LINE_HEADER,
    STATION_HEADER,
    STATION_DESCRIPTION_HEADER,
    OUTPUT_OPERATION_HEADER,
)
DECOMPOSITION_HEADERS = (*INPUT_HEADERS, TRANSLATED_OPERATION_HEADER)

SOS_HEADER = "SOS描述"
JES_HEADER = "JES描述"
STDS_HEADER = "STDS描述"
DECISION_HEADER = "Decisions"
CHARTCODE_HEADER = "Chart"
CV_HEADER = "增值|非增值"
FREQ_HEADER = "Freq"
TRACE_HEADER = "逐步的决策选择（trace）"
TIME_HEADER = "Time(s)"
DECISION_REASON_HEADER = "决策链选择的原因"

OUTPUT_HEADERS = (
    NUMBER_HEADER,
    PROJECT_HEADER,
    PRODUCT_MODEL_HEADER,
    LINE_HEADER,
    STATION_HEADER,
    STATION_DESCRIPTION_HEADER,
    SOS_HEADER,
    JES_HEADER,
    STDS_HEADER,
    DECISION_HEADER,
    CHARTCODE_HEADER,
    CV_HEADER,
    FREQ_HEADER,
    TIME_HEADER,
    DECISION_REASON_HEADER,
)
